ERROR: On characteristic rest_api read Station name. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorstations/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0bcf4190>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:16:48
ERROR: On characteristic read boarders. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorsboardervalue/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0bcf5450>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:16:58
ERROR: On characteristic send Log to Webapp. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /admin/auditLog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0bcf4d00>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:17:03
ERROR: On characteristic rest_api read Station name. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorstations/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0bcf64d0>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:17:08
ERROR: On characteristic read boarders. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorsboardervalue/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0bcf6c80>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:17:18
ERROR: On characteristic send Log to Webapp. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /admin/auditLog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0bcf6dd0>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:17:23
ERROR: On characteristic rest_api read Station name. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorstations/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0bcf7670>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:17:28
ERROR: On characteristic read boarders. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorsboardervalue/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0bcf78e0>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:17:38
ERROR: On characteristic send Log to Webapp. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /admin/auditLog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0bcf6b60>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:17:43
ERROR: On characteristic rest_api read Station name. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorstations/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0bcf5360>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:17:48
ERROR: On characteristic read boarders. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorsboardervalue/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0bcf7e20>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:17:58
ERROR: On characteristic send Log to Webapp. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /admin/auditLog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0bcf4670>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:18:03
ERROR: On characteristic rest_api read Station name. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorstations/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0bcf6aa0>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:18:08
ERROR: On characteristic read boarders. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorsboardervalue/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0bcf7ac0>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:18:18
ERROR: On characteristic send Log to Webapp. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /admin/auditLog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0bcf4250>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:18:23
ERROR: On characteristic rest_api read Station name. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorstations/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0bd4c1c0>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:18:28
INFO: Connected to device G4T2, Serivce uuid:	0000181a-0000-1000-8000-00805f9b34fb, Description:	Environmental Sensing at 05/16/23__18:18:35
INFO: Value for type LIGHT_INTENSITY on id 3 saved
INFO: Value for type HUMIDITY on id 2 saved
INFO: Value for type TEMPERATURE on id 1 saved
INFO: Value for type AIR_QUALITY on id 6 saved
INFO: Value for type SOIL_MOISTURE on id 4 saved
INFO: Value for type AIR_PRESSURE on id 5 saved
ERROR: On characteristic 00002a05-0000-1000-8000-00805f9b34fb. Error is [org.bluez.Error.NotPermitted] Read not permitted at 05/16/23__18:18:37
INFO: Disconnected at 05/16/23__18:18:37
ERROR: On characteristic read boarders. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorsboardervalue/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b8447f0>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:18:49
ERROR: On characteristic send Log to Webapp. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /admin/auditLog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b845210>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:18:54
ERROR: On characteristic rest_api read Station name. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorstations/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b8462c0>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:18:59
ERROR: On characteristic read boarders. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorsboardervalue/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b844700>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:19:09
ERROR: On characteristic send Log to Webapp. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /admin/auditLog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b8448b0>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:19:14
ERROR: On characteristic rest_api read Station name. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorstations/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b846bc0>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:19:19
ERROR: On characteristic read boarders. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorsboardervalue/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b847310>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:19:29
ERROR: On characteristic send Log to Webapp. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /admin/auditLog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b8473d0>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:19:34
ERROR: On characteristic rest_api read Station name. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorstations/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b846080>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:19:39
ERROR: On characteristic read boarders. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorsboardervalue/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b845b40>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:19:49
ERROR: On characteristic send Log to Webapp. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /admin/auditLog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b8445e0>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:19:55
ERROR: On characteristic rest_api read Station name. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorstations/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b847d30>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:20:00
ERROR: On characteristic read boarders. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorsboardervalue/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b844cd0>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:20:10
ERROR: On characteristic send Log to Webapp. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /admin/auditLog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b845060>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:20:15
ERROR: On characteristic rest_api read Station name. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorstations/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b845e10>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:20:20
ERROR: On characteristic read boarders. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorsboardervalue/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b846c50>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:20:30
ERROR: On characteristic send Log to Webapp. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /admin/auditLog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b847310>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:20:35
ERROR: On characteristic rest_api read Station name. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorstations/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b847160>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:20:40
INFO: Connected to device G4T2, Serivce uuid:	0000181a-0000-1000-8000-00805f9b34fb, Description:	Environmental Sensing at 05/16/23__18:20:48
INFO: Value for type LIGHT_INTENSITY on id 3 saved
INFO: Value for type HUMIDITY on id 2 saved
INFO: Value for type TEMPERATURE on id 1 saved
INFO: Value for type AIR_QUALITY on id 6 saved
INFO: Value for type SOIL_MOISTURE on id 4 saved
INFO: Value for type AIR_PRESSURE on id 5 saved
ERROR: On characteristic 00002a05-0000-1000-8000-00805f9b34fb. Error is [org.bluez.Error.NotPermitted] Read not permitted at 05/16/23__18:20:50
INFO: Disconnected at 05/16/23__18:20:50
INFO: Sensor with sensor_id 1 has been updated alarm_count to 3 
INFO: Sensor with sensor_id 2 has been updated alarm_count to 1 
ERROR: On characteristic write alarm_count to webapp. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/updatesensors (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b846770>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:20:58
INFO: Boarder values have been checked at 05/16/23__18:20:58
ERROR: On characteristic rest_api write values. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/measurements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b846cb0>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:20:59
ERROR: On characteristic read boarders. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorsboardervalue/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b845090>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:21:09
ERROR: On characteristic send Log to Webapp. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /admin/auditLog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b844850>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:21:14
ERROR: On characteristic rest_api read Station name. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorstations/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b8465f0>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:21:19
ERROR: On characteristic read boarders. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/sensorsboardervalue/50100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b847820>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:21:29
ERROR: On characteristic send Log to Webapp. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /admin/auditLog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e0b844e20>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/16/23__18:21:34
ERROR: On characteristic 00002a05-0000-1000-8000-00805f9b34fb. Error is [org.bluez.Error.NotPermitted] Read not permitted at 05/16/23__18:27:21
INFO: Connected to device G4T2, Serivce uuid:	0000181a-0000-1000-8000-00805f9b34fb, Description:	Environmental Sensing at 05/16/23__18:27:21
INFO: Value for type AIR_QUALITY on id 6 saved
INFO: Value for type LIGHT_INTENSITY on id 3 saved
INFO: Value for type AIR_PRESSURE on id 5 saved
INFO: Value for type SOIL_MOISTURE on id 4 saved
INFO: Value for type TEMPERATURE on id 1 saved
INFO: Value for type HUMIDITY on id 2 saved
INFO: Disconnected at 05/16/23__18:27:23
INFO: Sensor with sensor_id 1 has been updated alarm_count to 4 
INFO: Sensor with sensor_id 2 has been updated alarm_count to 2 
INFO: Boarder values have been checked at 05/16/23__18:27:31
INFO: Values of have been deleted at at 05/16/23__18:31:18
INFO: Sensor with sensor_id 1 has been updated upper_boarder to 10000 and lower_boarder to 0 
INFO: Sensor with sensor_id 2 has been updated upper_boarder to 10000 and lower_boarder to 0 
INFO: Sensor with sensor_id 3 has been updated upper_boarder to 10 and lower_boarder to 0 
ERROR: On characteristic rest_api read Station name. Error is HTTPConnectionPool(host='192.168.0.106', port=8080): Max retries exceeded with url: /api/sensorstations/252 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87250dbd90>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:12:56
ERROR: On characteristic read boarders. Error is HTTPConnectionPool(host='192.168.0.106', port=8080): Max retries exceeded with url: /api/sensorsboardervalue/252 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87250da6e0>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:13:06
ERROR: On characteristic send Log to Webapp. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /admin/auditLog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87250db010>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:13:11
ERROR: On characteristic rest_api read Station name. Error is HTTPConnectionPool(host='192.168.0.106', port=8080): Max retries exceeded with url: /api/sensorstations/252 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87250d9060>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:13:16
ERROR: On characteristic read boarders. Error is HTTPConnectionPool(host='192.168.0.106', port=8080): Max retries exceeded with url: /api/sensorsboardervalue/252 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87250d88b0>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:13:26
ERROR: On characteristic send Log to Webapp. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /admin/auditLog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87250d8760>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:13:31
ERROR: On characteristic rest_api read Station name. Error is HTTPConnectionPool(host='192.168.0.106', port=8080): Max retries exceeded with url: /api/sensorstations/252 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87250d97e0>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:13:36
ERROR: On characteristic read boarders. Error is HTTPConnectionPool(host='192.168.0.106', port=8080): Max retries exceeded with url: /api/sensorsboardervalue/252 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87250d9090>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:13:46
ERROR: On characteristic send Log to Webapp. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /admin/auditLog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87250d9570>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:13:51
ERROR: On characteristic rest_api read Station name. Error is HTTPConnectionPool(host='192.168.0.106', port=8080): Max retries exceeded with url: /api/sensorstations/252 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87250da1d0>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:13:56
ERROR: Could not find device with name G4T2 at 05/18/23__08:14:12
INFO: Boarder values have been checked at 05/18/23__08:14:17
ERROR: On characteristic rest_api write values. Error is HTTPConnectionPool(host='192.168.0.106', port=8080): Max retries exceeded with url: /api/measurements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8724c27eb0>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:14:18
ERROR: On characteristic read boarders. Error is HTTPConnectionPool(host='192.168.0.106', port=8080): Max retries exceeded with url: /api/sensorsboardervalue/252 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8724c6c190>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:14:28
ERROR: On characteristic send Log to Webapp. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /admin/auditLog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8724c6cb50>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:14:33
ERROR: On characteristic rest_api read Station name. Error is HTTPConnectionPool(host='192.168.0.106', port=8080): Max retries exceeded with url: /api/sensorstations/252 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8724c27640>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:14:38
ERROR: On characteristic read boarders. Error is HTTPConnectionPool(host='192.168.0.106', port=8080): Max retries exceeded with url: /api/sensorsboardervalue/252 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8724c6ce50>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:14:48
ERROR: On characteristic send Log to Webapp. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /admin/auditLog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8724c6c190>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:14:53
ERROR: On characteristic rest_api read Station name. Error is HTTPConnectionPool(host='192.168.0.106', port=8080): Max retries exceeded with url: /api/sensorstations/252 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8724c6de70>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:14:58
ERROR: On characteristic read boarders. Error is HTTPConnectionPool(host='192.168.0.106', port=8080): Max retries exceeded with url: /api/sensorsboardervalue/252 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8724c6e470>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:15:08
ERROR: On characteristic send Log to Webapp. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /admin/auditLog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8724c6d840>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:15:13
ERROR: On characteristic rest_api read Station name. Error is HTTPConnectionPool(host='192.168.0.106', port=8080): Max retries exceeded with url: /api/sensorstations/252 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8724c6c7c0>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:15:18
ERROR: On characteristic read boarders. Error is HTTPConnectionPool(host='192.168.0.106', port=8080): Max retries exceeded with url: /api/sensorsboardervalue/252 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8724c6e680>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:15:28
ERROR: On characteristic send Log to Webapp. Error is HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /admin/auditLog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8724c6e7a0>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:15:33
ERROR: On characteristic rest_api read Station name. Error is HTTPConnectionPool(host='192.168.0.106', port=8080): Max retries exceeded with url: /api/sensorstations/252 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8724c6f850>: Failed to establish a new connection: [Errno 111] Connection refused')) at 05/18/23__08:15:38
ERROR: Could not find device with name G4T2 at 05/18/23__08:15:53
Sensor Station G4T2 has been deleted at 05/18/23__08:18:29
ERROR: On characteristic Filter New Stations. Error is 'NoneType' object has no attribute 'remove' at 05/18/23__08:18:29
ERROR: On characteristic rest_api read Station name. Error is object of type 'NoneType' has no len() at 05/18/23__08:18:29
ERROR: On characteristic call sending interval. Error is 'measurementInterval' at 05/18/23__08:18:39
ERROR: On characteristic rest_api read Station name. Error is object of type 'NoneType' has no len() at 05/18/23__08:18:56
ERROR: On characteristic call sending interval. Error is 'measurementInterval' at 05/18/23__08:19:07
ERROR: On characteristic rest_api read Station name. Error is object of type 'NoneType' has no len() at 05/18/23__08:21:17
ERROR: On characteristic rest_api read Station name. Error is object of type 'NoneType' has no len() at 05/18/23__08:26:55
